services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/cache:/data
  db:
    image: postgres
    volumes:
      -  ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web-chat:
    build: .
    command: python /code/chat_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE=chat_project.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
